### ISSUE TITLE
Add PPM to pt_prcs_domain.rb

### ISSUE THREAD

**Issue by jradwan** [bloodmc/pt_dpk_patches#4]
Patch enhancement suggestion:

As delivered by Oracle, the performance monitor feature  is missing from modules\pt_config\lib\puppet\type\pt_prcs_domain.rb:
```
        prcs_features =
          [ "MSTRSRV", "APPENG", "KIOSK", "DOMAIN_GW", "SERVER_EVENTS" ]
```
Changing it to this:
```         
          [ "MSTRSRV", "APPENG", "KIOSK", "DOMAIN_GW", "SERVER_EVENTS", "PPM" ]
```
allows you to turn off PPM for the Process Scheduler domain via psft_customizations.yaml:
```
    feature_settings:
      MSTRSRV:       "No"
      APPENG:        "No"   
      SERVER_EVENTS: "Yes"
      DOMAIN_GW:     "Yes" 
-->   PPM:           "No"   <--
```

**Comment by bloodmc** [comment]
Fixed in PR https://github.com/bloodmc/pt_dpk_patches/pull/6
